exporter:
  channel_assignment:
    {
      "labels":
        [
          [0, 31, 1],
          [
            ADJUST_RANGE_0_1_TO_0_255,
            TO_UINT8,
            TO_CPU,
            TO_NUMPY,
            MAKE_LABELS_WITH_ADDED_BG,
          ],
        ],
      "raw":
        [
          [31, 32, 1],
          [ADJUST_RANGE_NEG1_1_TO_0_255, TO_UINT8, TO_CPU, TO_NUMPY],
        ],
    }
  sample_batch_size: 64
  file_format: .zarr
  sample_digits: 6
  dir: samples_138380027
  threshold: 10
checkpoint: 141
eval_batch_size: 128
num_samples: 52480
experiment_run_id: 55da5f83a58a4cb982a273c9687a7132
