predictor:
  milestone: 18
  batch_size: 64
  dataloader_nworkers: 10
  include_input: True
data:
  data_type: simple
  folder: /nrs/saalfeld/heinrichl/data/cellmap_labels/inference/jrc_sum159-1
experiment_run_id: 830eff13f552457c8f20ff2fd25aef09
exporter:
  channel_assignment:
    {
      "raw":
        [
          [0, 1, 1],
          [ADJUST_RANGE_NEG1_1_TO_0_255, TO_UINT8, TO_CPU, TO_NUMPY, GRIDDIFY],
        ],
      "label":
        [
          [1, 34, 1],
          [
            ADJUST_RANGE_0_1_TO_0_255,
            TO_UINT8,
            TO_CPU,
            TO_NUMPY,
            COLORIZE,
            GRIDDIFY,
          ],
        ],
    }
  threshold: 10
  colors:
    [
      [0, 0, 0],
      [50, 50, 50],
      [100, 100, 100],
      [255, 128, 0],
      [128, 64, 0],
      [220, 172, 104],
      [0, 132, 255],
      [0, 66, 128],
      [255, 0, 0],
      [128, 0, 0],
      [0, 0, 255],
      [0, 0, 128],
      [255, 216, 0],
      [128, 108, 0],
      [134, 164, 247],
      [79, 66, 252],
      [57, 215, 46],
      [51, 128, 46],
      [85, 254, 219],
      [6, 185, 157],
      [9, 128, 0],
      [5, 77, 0],
      [175, 249, 111],
      [252, 144, 211],
      [168, 55, 188],
      [84, 23, 94],
      [204, 0, 102],
      [102, 0, 51],
      [255, 0, 255],
      [247, 82, 104],
      [255, 255, 255],
      [128, 128, 128],
    ]
  sample_batch_size: 25
  file_format: .png
  dir: inference_jrc_sum159-1
