image_size: 128
diffusion:
  timesteps: 1000
  sampling_timesteps: 250
  auto_normalize: False
  channel_weights: [
            1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,31
        ]
architecture:
  dim: 64
  channels: 32
  dim_mults: [1,2,4,8]
training:
  train_batch_size: 96
  train_lr: 8e-5
  train_num_steps: 700000
  gradient_accumulate_every: 1
  ema_decay: 0.995
  amp: False
  calculate_fid: False
  dataloader_nworkers: 30
  persitent_workers: True
  prefetch_factor: 5

data:
  data_type: "cellmap3das2d"
  data_paths: ["/nrs/cellmap/data/jrc_hela-2/jrc_hela-2.n5",
               "/nrs/cellmap/data/jrc_hela-3/jrc_hela-3.n5",
               "/nrs/cellmap/data/jrc_macrophage-2/jrc_macrophage-2.n5",
               "/nrs/cellmap/data/jrc_sum159-1/jrc_sum159-1.n5",
               "/nrs/cellmap/data/jrc_jurkat-1/jrc_jurkat-1.n5"
  ]
  raw_datasets: [None, None, None, None, None]
  class_list: [
            "ecs",
            "pm",
            "mito_mem",
            "mito_lum",
            "mito_ribo",
            "golgi_mem",
            "golgi_lum",
            "ves_mem",
            "ves_lum",
            "endo_mem",
            "endo_lum",
            "lyso_mem",
            "lyso_lum",
            "ld_mem",
            "ld_lum",
            "er_mem",
            "er_lum",
            "eres_mem",
            "eres_lum",
            "ne_mem",
            "ne_lum",
            "np_out",
            "np_in",
            "hchrom",
            "nhchrom",
            "echrom",
            "nechrom",
            "nucpl",
            "nucleo",
            "mt_out",
            "mt_in",
        ]
  scale: {"x":4, "y":4, "z":4}
  augment_horizontal_flip: True
  augment_vertical_flip: True
  annotation_paths: ["/home/heinrichl@hhmi.org/data/cellmap/reslicing/jrc_hela-2/groundtruth.zarr",
                     "/home/heinrichl@hhmi.org/data/cellmap/reslicing/jrc_hela-3/groundtruth.zarr",
                     "/home/heinrichl@hhmi.org/data/cellmap/reslicing/jrc_macrophage-2/groundtruth.zarr",
                     "/home/heinrichl@hhmi.org/data/cellmap/reslicing/jrc_sum159-1/groundtruth.zarr",
                     "/home/heinrichl@hhmi.org/data/cellmap/reslicing/jrc_jurkat-1/groundtruth.zarr"]
  dask_workers: 1
  crop_lists: [["crop1", "crop113", "crop13", "crop14", "crop15", "crop155", "crop16", "crop18", "crop19", "crop23", "crop28", "crop3", "crop4", "crop6", "crop7", "crop8"], ["crop101", "crop111", "crop181", "crop27", "crop33", "crop34", "crop50", "crop51"], ["crop109", "crop110", "crop31", "crop32", "crop39", "crop40", "crop42", "crop48", "crop49"], ["crop20", "crop21", "crop22", "crop80"], ["crop107", "crop112", "crop126", "crop180", "crop182", "crop35", "crop36", "crop37", "crop38", "crop43", "crop47"]]
  pre_load: True
  contrast_adjust: True
  
tracking:
  experiment_name: em+label_generation
  tracking_uri: file:///nrs/saalfeld/heinrichl/mlflow_tracking/diffusion
  run_name: exp06
  continue_run_id: c8aa6282c12441068a0ec79137130f89